Add deploy scripts utilizing the hardhat-deploy plugin
fractal-framework/fractal-contracts pull request #58
Opened 2022-03-15 14:24 UTC by tbwebb22

- Added deploy scripts utilizing the hardhat-deploy plugin
- Configured it such that only the scripts within the deploy/core run automatically as part of the deploy process
- Scripts outside of the core/deploy folder, such as deploy_dao in the deploy/DAO folder will need to be called manually to run

I'm not attaching this PR to Issue #55 "Deploy Scripts" since these deploy scripts will need to be updated over time as modules are added to the codebase.

2022-03-15 14:31 UTC, adamgall commented on test/DAOFactory.test.ts
> +describe.only("DAOFactory", () => {
@tbwebb22 you probably didn't mean to commit this

2022-03-15 14:44 UTC, adamgall requested changes
@tbwebb22 please add information to the readme, explaining how to utilize these scripts to get a (local) system up and running.

While you're in there, it looks like there's a lot of stale info in the readme as well. At the very lease, please delete stuff that's no longer relevant.

2022-03-16 19:59 UTC, tbwebb22 commented
Added a Hardhat task for creating DAOs and updated the ReadMe.

2022-03-16 20:05 UTC, adamgall approved these changes

2022-03-17 13:55 UTC, merged